### ISSUE TITLE
Duplicate matches

### ISSUE THREAD

**Issue by rasmusbuchholdt** [office-rivals/mmr-project#52]
Add a check that tells the user if a similar match has been entered recently so we don't get these duplicates:
![image](https://github.com/madsthom/mmr-project/assets/9290148/6302ec71-57ba-4abb-a399-80b06ad8598c)

**Comment by bruunand** [comment]
Further suggestion: punish users who try to submit duplicate matches by reducing their MMR. This will encourage communication between our colleagues.
